name: veridian-prod

x-witness-common: &witness-common
  profiles: [witness,production,local]
  restart: unless-stopped
  image: ${WITNESS_IMAGE:-weboftrust/keri:1.1.26}
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONIOENCODING=UTF-8
    - INITIAL_HTTP_PORT=5642
    - INITIAL_TCP_PORT=5632
    - KERI_VAR_DIR=/usr/local/var/keri
    - KERI_SCRIPT_DIR=/usr/local/var/keri/scripts
    - LOG_LEVEL=INFO
  entrypoint: ["bash", "-c", "export WITNESS_NO=$$(hostname | awk -F- '{print $$NF}'); exec kli witness start --loglevel $${LOG_LEVEL} --name wit$${WITNESS_NO} --alias wit$${WITNESS_NO} -H $$(( INITIAL_HTTP_PORT + WITNESS_NO ))"]
  volumes:
    - witnesses-config:/usr/local/var/keri

x-keria-common: &keria-common
  restart: unless-stopped
  image: ${KERIA_IMAGE:-cardanofoundation/cf-idw-keria:main}
  environment:
    - KERI_AGENT_CORS=${KERI_AGENT_CORS:-true}
    - KERIA_PASSCODE=${KERIA_PASSCODE:-CHANGEME}
    - ALLOW_INTRODUCTIONS=${ALLOW_INTRODUCTIONS:-true}
    - REMOTE_SIGNING=${REMOTE_SIGNING:-true}
  volumes:
    - keria-data:/usr/local/var/keri
    - keria-config:/keria/scripts/keri/cf
  entrypoint: keria start --config-file backer-oobis --config-dir ./scripts --loglevel INFO

services:
  keria-init:
    profiles: [keria-init]
    image: "rcmorano/alpine-bash-jq-curl"
    environment:
      - KERIA_PASSCODE=${KERIA_PASSCODE:-DLDRW3f108LaQB2qscJOd}
      - KERIA_CURLS=${KERIA_CURLS:-http://keria-prod:3902}
      - KERIA_IURLS=${KERIA_IURLS:-http://witness:5642/oobi/dummy1 http://witness:5643/oobi/dummy2}
    volumes:
      - keria-config:/config
    configs:
      - source: keria-init_sh
        target: /keria-init.sh
      - source: backer-oobis_json_tpl
        target: /configmap/backer-oobis.json.tpl
    entrypoint: ["bash", "/keria-init.sh"]

  keria-local:
    profiles: [keria-local,local]
    <<: *keria-common
    ports:
      - 3904:3901
      - 3905:3902
      - 3906:3903

  keria:
    profiles: [keria,production]
    <<: *keria-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.keria.rule=Host(`${KERIA_HOST:-keria}`)"
      - "traefik.http.routers.keria.entrypoints=websecure"
      - "traefik.http.routers.keria.tls.certresolver=myresolver"
      - "traefik.http.routers.keria.service=keria"
      - "traefik.http.services.keria.loadbalancer.server.port=3901"
      - "traefik.http.routers.keria-http.rule=Host(`${KERIA_HOST:-keria}`)"
      - "traefik.http.routers.keria-http.entrypoints=web"
      - "traefik.http.routers.keria-http.middlewares=redirect-to-https"

      - "traefik.http.routers.keria-ext.rule=Host(`${KERIA_EXT_HOST:-keria-ext}`)"
      - "traefik.http.routers.keria-ext.entrypoints=websecure"
      - "traefik.http.routers.keria-ext.tls.certresolver=myresolver"
      - "traefik.http.routers.keria-ext.service=keria-ext"
      - "traefik.http.services.keria-ext.loadbalancer.server.port=3902"
      - "traefik.http.routers.keria-ext-http.rule=Host(`${KERIA_EXT_HOST:-keria-ext}`)"
      - "traefik.http.routers.keria-ext-http.entrypoints=web"
      - "traefik.http.routers.keria-ext-http.middlewares=redirect-to-https"

      - "traefik.http.routers.keria-boot.rule=Host(`${KERIA_BOOT_HOST:-keria-boot}`)"
      - "traefik.http.routers.keria-boot.entrypoints=websecure"
      - "traefik.http.routers.keria-boot.tls.certresolver=myresolver"
      - "traefik.http.routers.keria-boot.service=keria-boot"
      - "traefik.http.services.keria-boot.loadbalancer.server.port=3903"
      - "traefik.http.routers.keria-boot-http.rule=Host(`${KERIA_BOOT_HOST:-keria-boot}`)"
      - "traefik.http.routers.keria-boot-http.entrypoints=web"
      - "traefik.http.routers.keria-boot-http.middlewares=redirect-to-https"

  witness-init:
    profiles: [witness-init]
    restart: no
    image: cardanofoundation/cf-idw-witness:main
    environment:
      - KERI_VAR_DIR=/usr/local/var/keri
      - KERI_SCRIPT_DIR=/usr/local/var/keri/scripts
      - KERIA_CURLS_PROTO=${KERIA_CURLS_PROTO:-https}
      - KERIA_CURLS_EXTERNAL_HOST_TLD=${PUBLIC_DOMAIN:-example.com}
      - WITNESS_COUNT=${WITNESS_COUNT:-6}
      - DEPLOYMENT_MODE=${DEPLOYMENT_MODE:-cloud}
      - BASE_HTTP_PORT=5642
    volumes:
      - witnesses-config:/usr/local/var/keri
    configs:
      - source: witness-init_sh
        target: /configmap/witness-init.sh
      - source: witness_json_tpl
        target: /configmap/witness.json.tpl
      - source: wil-witness-sample.json
        target: /configmap/wil-witness-sample.json
    entrypoint: ["bash", "-c", "bash /configmap/witness-init.sh"]

  witness-0:
    profiles: [witness,production,local]
    hostname: witness-0
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness0.rule=Host(`witness-0.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness0.entrypoints=websecure"
      - "traefik.http.routers.witness0.tls.certresolver=myresolver"
      - "traefik.http.services.witness0.loadbalancer.server.port=5642"
      - "traefik.http.routers.witness0-http.rule=Host(`witness-0.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness0-http.entrypoints=web"
      - "traefik.http.routers.witness0-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  witness-1:
    profiles: [witness,production,local]
    hostname: witness-1
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness1.rule=Host(`witness-1.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness1.entrypoints=websecure"
      - "traefik.http.routers.witness1.tls.certresolver=myresolver"
      - "traefik.http.services.witness1.loadbalancer.server.port=5643"
      - "traefik.http.routers.witness1-http.rule=Host(`witness-1.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness1-http.entrypoints=web"
      - "traefik.http.routers.witness1-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  witness-2:
    profiles: [witness,production,local]
    hostname: witness-2
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness2.rule=Host(`witness-2.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness2.entrypoints=websecure"
      - "traefik.http.routers.witness2.tls.certresolver=myresolver"
      - "traefik.http.services.witness2.loadbalancer.server.port=5644"
      - "traefik.http.routers.witness2-http.rule=Host(`witness-2.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness2-http.entrypoints=web"
      - "traefik.http.routers.witness2-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  witness-3:
    profiles: [witness,production,local]
    hostname: witness-3
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness3.rule=Host(`witness-3.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness3.entrypoints=websecure"
      - "traefik.http.routers.witness3.tls.certresolver=myresolver"
      - "traefik.http.services.witness3.loadbalancer.server.port=5645"
      - "traefik.http.routers.witness3-http.rule=Host(`witness-3.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness3-http.entrypoints=web"
      - "traefik.http.routers.witness3-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  witness-4:
    profiles: [witness,production,local]
    hostname: witness-4
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness4.rule=Host(`witness-4.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness4.entrypoints=websecure"
      - "traefik.http.routers.witness4.tls.certresolver=myresolver"
      - "traefik.http.services.witness4.loadbalancer.server.port=5646"
      - "traefik.http.routers.witness4-http.rule=Host(`witness-4.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness4-http.entrypoints=web"
      - "traefik.http.routers.witness4-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  witness-5:
    profiles: [witness,production,local]
    hostname: witness-5
    <<: *witness-common
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.witness5.rule=Host(`witness-5.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness5.entrypoints=websecure"
      - "traefik.http.routers.witness5.tls.certresolver=myresolver"
      - "traefik.http.services.witness5.loadbalancer.server.port=5647"
      - "traefik.http.routers.witness5-http.rule=Host(`witness-5.${PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.witness5-http.entrypoints=web"
      - "traefik.http.routers.witness5-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  cred-issuance:
    profiles: [cred-issuance,production,local]
    image: ${CRED_IMAGE:-cardanofoundation/cf-cred-issuance:main}
    restart: unless-stopped
    environment:
      - OOBI_ENDPOINT=${CRED_OOBI_ENDPOINT:-http://cred-issuance:3001}
      - KERIA_ENDPOINT=${CRED_KERIA_ENDPOINT:-http://keria:3901}
      - KERIA_BOOT_ENDPOINT=${CRED_KERIA_BOOT_ENDPOINT:-http://keria:3903}
    volumes:
      - issuer-server-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.credentials.rule=Host(`${CRED_HOST:-cred-issuance}`)"
      - "traefik.http.routers.credentials.entrypoints=websecure"
      - "traefik.http.routers.credentials.tls.certresolver=myresolver"
      - "traefik.http.services.credentials.loadbalancer.server.port=3001"
      - "traefik.http.routers.credentials-http.rule=Host(`${CRED_HOST:-cred-issuance}`)"
      - "traefik.http.routers.credentials-http.entrypoints=web"
      - "traefik.http.routers.credentials-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  cred-issuance-ui:
    profiles: [cred-issuance,production,local]
    image: ${CRED_UI_IMAGE:-cardanofoundation/cf-cred-issuance-ui:main}
    restart: unless-stopped
    environment:
      - VITE_SERVER_URL=${CRED_UI_SERVER_URL:-http://localhost:3001}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.credentials-ui.rule=Host(`${CRED_UI_HOST:-cred-issuance-ui}`)"
      - "traefik.http.routers.credentials-ui.entrypoints=websecure"
      - "traefik.http.routers.credentials-ui.tls.certresolver=myresolver"
      - "traefik.http.services.credentials-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.credentials-ui-http.rule=Host(`${CRED_UI_HOST:-cred-issuance-ui}`)"
      - "traefik.http.routers.credentials-ui-http.entrypoints=web"
      - "traefik.http.routers.credentials-ui-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  traefik:
    profiles: [traefik,production]
    image: "traefik:v3.3.5"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog.filepath=/dev/stdout"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_ADMIN_EMAIL:-acme@example.com}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      #- "8080:8080"
    volumes:
      - "/var/lib/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  keria-data:
  keria-config:
  issuer-server-data:
  witnesses-config:

configs:
  backer-oobis_json_tpl:
    content: |
      {
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "keria": {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "curls": $${KERIA_RENDERED_CURLS}
        },
        "iurls": $${KERIA_RENDERED_IURLS}
      }

  keria-init_sh:
    content: |
      #!/bin/sh
      set -xe
      export KERIA_RENDERED_CURLS=$$(for keria_curl in $${KERIA_CURLS}; do echo $$keria_curl; done | jq -cRn '[inputs]')
      export KERIA_RENDERED_IURLS=$$(for keria_iurl in $${KERIA_IURLS}; do echo $$keria_iurl; done | jq -cRn '[inputs]')
      envsubst < /configmap/backer-oobis.json.tpl > /config/backer-oobis.json

  witness_json_tpl:
    content: |
      {
        "$${WITNESS_NAME}": {
          "dt": "2022-01-20T12:57:59.823350+00:00",
          "curls": $${KERIA_RENDERED_CURLS}
        },
        "dt": "2022-01-20T12:57:59.823350+00:00",
        "iurls": [
        ]
      }

  wil-witness-sample.json:
    content: |
      {
        "transferable": false,
        "wits": [],
        "icount": 1,
        "ncount": 1,
        "isith": "1",
        "nsith": "1"
      }

  witness-init_sh:
    content: |
      #!/bin/bash
      set -x
      for wit in $$(seq 0 $$(( WITNESS_COUNT - 1 )));
      do
        WITNESS_COUNTER=$$wit
        if [ ! -e $${KERI_VAR_DIR}/db/wit$${WITNESS_COUNTER}/data.mdb ]; then
          mkdir -p $${KERI_VAR_DIR}/data
          mkdir -p $${KERI_SCRIPT_DIR}/keri/cf
          set -e
          
          # Set KERIA_CURLS based on deployment mode
          if [ "$${DEPLOYMENT_MODE}" = "local" ]; then
            export KERIA_CURLS="$${KERIA_CURLS_PROTO}://witness-$${WITNESS_COUNTER}:$$(( BASE_HTTP_PORT + WITNESS_COUNTER ))"
            echo "Local deployment mode - Setting KERIA_CURLS to: $${KERIA_CURLS}"
          else
            export KERIA_CURLS="$${KERIA_CURLS_PROTO}://witness-$${WITNESS_COUNTER}.$${KERIA_CURLS_EXTERNAL_HOST_TLD}"
            echo "Cloud deployment mode - Setting KERIA_CURLS to: $${KERIA_CURLS}"
          fi
          
          echo "Rendering KERIA_CURLS..."
          export KERIA_RENDERED_CURLS=$$(for keria_curl in $${KERIA_CURLS}; do echo $$keria_curl; done | jq -cRn '[inputs]')
          echo "KERIA_RENDERED_CURLS: $${KERIA_RENDERED_CURLS}"
          
          export WITNESS_NAME="wit$${WITNESS_COUNTER}"
          envsubst < /configmap/witness.json.tpl > $${KERI_SCRIPT_DIR}/keri/cf/$${WITNESS_NAME}.json
          
          echo "Generated config file contents:"
          cat $${KERI_SCRIPT_DIR}/keri/cf/$${WITNESS_NAME}.json
          kli init --name $${WITNESS_NAME} --nopasscode --config-dir $${KERI_SCRIPT_DIR} --config-file $${WITNESS_NAME}.json
          kli incept --name $${WITNESS_NAME} --alias $${WITNESS_NAME} --config $${KERI_SCRIPT_DIR} --file /configmap/wil-witness-sample.json
          
          echo "Witness $${WITNESS_NAME} initialization completed."
        else
          echo "Config file already exists for witness $${WITNESS_COUNTER}, skipping initialization."
        fi
      done
