# Mobile Security Configuration
# This file defines security scanning parameters and thresholds

# Vulnerability Thresholds
vulnerabilities:
  max_critical: 0      # Fail immediately on critical vulnerabilities
  max_high: 5          # Allow up to 5 high severity vulnerabilities
  max_medium: 10       # Allow up to 10 medium severity vulnerabilities
  max_low: 20          # Allow up to 20 low severity vulnerabilities

# Security Checks Configuration
security_checks:
  npm_audit: true
  npm_outdated: true
  ios_vulnerabilities: true
  android_vulnerabilities: true
  sensitive_files: true
  capacitor_config: true

# Sensitive File Patterns
sensitive_files:
  - "google-services.json"
  - "GoogleService-Info.plist"
  - "*.keystore"
  - "*.jks"
  - "*.p12"
  - "*.mobileprovision"
  - "*.pem"
  - "*.key"

# Known Vulnerable Libraries
vulnerable_libraries:
  ios:
    - "AFNetworking"
    - "SDWebImage"
    - "Realm"
    - "CocoaLumberjack"
    - "GoogleMLKit"
    - "MLKitBarcodeScanning"
  
  android:
    - "okhttp"
    - "retrofit"
    - "glide"
    - "picasso"
    - "volley"
    - "universal-image-loader"

# Security Settings to Check
security_settings:
  android:
    - "debuggable"
    - "allowBackup"
    - "usesCleartextTraffic"
  
  capacitor:
    - "allowNavigation"
    - "server"
    - "cleartext"

# Reporting Configuration
reporting:
  generate_html: true
  generate_markdown: false
  include_technical_details: true
  include_recommendations: true

# Environment-Specific Settings
environments:
  development:
    fail_on_critical: false
    fail_on_high: false
    max_vulnerabilities: 20
  
  production:
    fail_on_critical: true
    fail_on_high: true
    max_vulnerabilities: 5 