const ISSUER_AID_NAME = "issuer";
const HOLDER_AID_NAME = "holder";
const QVI_SCHEMA_SAID = "EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao";
const RARE_EVO_DEMO_SCHEMA_SAID =
  "EJxnJdxkHbRw2wVFNe4IUOPLt8fEtg9Sr3WyTjlgKoIb";
const LE_SCHEMA_SAID = "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY";

export {
  ISSUER_AID_NAME,
  HOLDER_AID_NAME,
  QVI_SCHEMA_SAID,
  RARE_EVO_DEMO_SCHEMA_SAID,
  LE_SCHEMA_SAID,
};
