name: build-test

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
      - develop
      - release/**

env:
  NODE_OPTIONS: "--max_old_space_size=8192"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
          submodules: recursive

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: "package.json"

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint (Core Only)
      run: npx eslint src/core --ext .ts,.tsx

    - name: Run unit tests

      run: npm run test

    - name: 🔨 Build project
      run: npm run build
