name: OWASP Dependency-Check (Android)

on:
  push:
    paths:
      - "android/**"
      - "**/*.gradle"
      - "**/gradle*.properties"
  pull_request:
    types: [ opened, synchronize ]

jobs:
  depcheck-android:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      # Run OWASP Dependency-Check via the official Action
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "veridian-wallet-android"
          path: "android"
          format: "ALL"
          out: "reports"
          args: "--failOnCVSS 7 --nvdApiKey ${{ env.NVD_API_KEY }} --disableCentral"
        continue-on-error: false

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-android-report
          path: "reports/dependency-check-report.html"

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "reports/dependency-check-report.sarif"
