name: Mobile Dependency Security Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'ios/**'
      - 'android/**'
      - 'capacitor.config.ts'
      - 'mobile-security-config.yaml'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'ios/**'
      - 'android/**'
      - 'capacitor.config.ts'
      - 'mobile-security-config.yaml'

jobs:
  mobile-security-audit:
    name: Mobile Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install --no-audit --no-fund
        
      - name: Build project
        run: npm run build
        
      - name: Sync Capacitor platforms
        run: |
          npx --yes cap sync ios
          npx --yes cap sync android
          
      - name: Install iOS dependencies
        run: |
          cd ios/App
          pod install --repo-update
          
      - name: Run mobile dependency audit
        run: |
          chmod +x scripts/mobile-dependency-audit.sh
          ./scripts/mobile-dependency-audit.sh
          
      - name: Check for sensitive files in mobile directories
        run: |
          echo "🔍 Checking for sensitive files in mobile directories..."
          
          # Check for sensitive Android files
          if find android -name "google-services.json" -o -name "*.keystore" -o -name "*.jks" | grep -q .; then
            echo "⚠️ Found sensitive Android files:"
            find android -name "google-services.json" -o -name "*.keystore" -o -name "*.jks"
          fi
          
          # Check for sensitive iOS files
          if find ios -name "GoogleService-Info.plist" -o -name "*.p12" -o -name "*.mobileprovision" | grep -q .; then
            echo "⚠️ Found sensitive iOS files:"
            find ios -name "GoogleService-Info.plist" -o -name "*.p12" -o -name "*.mobileprovision"
          fi
          
          echo "✅ Sensitive file check completed"
          
      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mobile-security-audit-results
          path: |
            android/build/reports/
            ios/App/Podfile.lock
          retention-days: 30 